name: steker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3+1
  dio: ^3.0.10
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  firebase_storage: ^5.1.0
  flutter_icons: ^1.1.0
  google_sign_in: ^4.5.6
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  whatsapp_stickers: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tray_img.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
